- Discussione Specifica Tecnica
  - Indicazione soddisfacimento requisiti 
  - Inserimento immagini classi
- Discussione Piano di Qualifica
  - Inserimento test di unità e accettazione 
  - Aggiornamento test di sistema
- Discussione situazione codifica, test e deployment
- Discussione situazione Manuale Sviluppatore e Manuale Utente