- Verbale
- Discussione incontro con Cardin
- Discussione progettazione
  - Discussione nome classi
  - Discussione Dati API/Controller
  - Discussione operazioni Servizi
  - Discussione operazione Persistence
    - Discussione progettazione e implementazione updateElementiDomandaSet
- Discussione test e automazioni
  - pytest
  - docker e web
- Issues aggiunte