=== Glossario

Il glossario è un documento centrale per il progetto, concepito per raccogliere e definire in modo chiaro e univoco tutti i termini, abbreviazioni e acronimi utilizzati nei vari documenti. Questo strumento ha l’obiettivo di garantire una comunicazione uniforme all'interno del team e una comprensione condivisa del linguaggio tecnico e specifico del progetto. La gestione del glossario richiede la collaborazione attiva di tutti i membri del gruppo. Ogni volta che un termine, una parola o un acronimo viene introdotto in un documento, il membro che lo utilizza ha la responsabilità di aggiornare il glossario, aggiungendo la nuova voce con una definizione chiara e precisa. Questo approccio assicura che il glossario rimanga costantemente aggiornato e rappresenti un riferimento affidabile per tutto il team. Il glossario non solo facilita il lavoro del team durante la redazione e la revisione dei documenti, ma rappresenta anche un valore aggiunto per chiunque, interno o esterno al progetto, debba consultare la documentazione. La sua consultazione permette di evitare fraintendimenti, accelerare i processi decisionali e mantenere coerenza terminologica nei vari aspetti del progetto.

==== Suddivisione delle parole

La struttura è basata su un sistema alfabetico, dove ogni lettera rappresenta una sezione che raccoglie le voci corrispondenti. Ogni termine incluso nel glossario è accompagnato da una definizione concisa e precisa, che spiega il suo significato nel contesto del progetto. All’inizio del documento è presente una tabella delle versioni, che tiene traccia delle modifiche apportate al glossario, con indicazioni su data, descrizione degli aggiornamenti, autore, verificatore e validatore. Questo sistema assicura che il glossario sia costantemente aggiornato e validato in modo collaborativo. La struttura include un indice dettagliato che facilita la navigazione tra le sezioni. Ogni termine è descritto con il massimo livello di dettaglio necessario per garantire una comprensione condivisa.

==== Aggiunta di un Termine

Per aggiungere un termine al glossario, è necessario inserire una coppia di valori, nel file Glossario.typ nella struttura dizionario (dict) denominata glossario. Il primo valore è composto dall'acronimo/abbreviazione e/o il termine per esteso, se sono presenti entrambi devono essere separati dal carattere "|". La seconda deve essere una descrizione chiara, breve e dettagliata, che spiega il significato del termine e il suo utilizzo nel contesto del progetto.
La funzione inDict presente nel file functions.typ si occupa di inserire la "G" a pedice dopo ogni occorrenza del Primo dei 2 valori nei vari documenti.
