= Documentazione

#include "documentazione/struttura.typ"
#include "documentazione/versionamento.typ"
#include "documentazione/nomenclatura.typ"
#include "documentazione/processi.typ"
#include "documentazione/verbali.typ"
#include "documentazione/utilizzoTemplate.typ"
#include "documentazione/github.typ"
#include "documentazione/riunioni.typ"
#include "documentazione/pianoDiProgetto.typ"
#include "documentazione/pianoDiQualifica.typ"
#include "documentazione/tracciamentoOre.typ"
#include "documentazione/glossario.typ"
#include "documentazione/analisiDeiRequisiti.typ"
